package modelo;

public enum Evento {
    CAMBIO_FICHAS_JUGADOR,
    CAMBIO_FICHAS_JUGADOR1,
    CAMBIO_FICHAS_JUGADOR2,
    INICIAR_JUEGO,
    JUGADOR_JUGO_FICHA,
    ACTUALIZAR_TABLERO,
    PASAR_TURNO,
    CAMBIO_RONDA,
    FIN_DEL_JUEGO
}
